apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fulfillorderack
spec:
  replicas: 10
  template:
    metadata:
      labels:
        task: fulfillorderack
        k8s-app: fulfillorderack
    spec:
      containers:
      - name: fulfillorderack
        image: aksregistryetoro.azurecr.io/fulfillorderack:latest
        env:
          - name: APPINSIGHT_KEY
            value: "ae038c96-cd43-4643-9814-81a7ea378e48"
          - name: CHALLENGEAPPINSIGHTS_KEY
            value: "534fd36c-889c-4cce-977a-49ccd6d6e5cf"
          - name: TEAMNAME
            value: "team6"
          - name: MONGOURL
            value: "mongodb://etorodb:Aa123456!@etoro-mongo-mongodb/database.default"
        ports:
          - containerPort: 8080
            protocol: TCP
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/orders"
            name: etoro-storage
      nodeSelector:
        beta.kubernetes.io/os: linux
      volumes:
        - name: etoro-storage
          persistentVolumeClaim:
            claimName: myclaim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/name: fulfillorderack-service
  name: fulfillorderack
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  type: LoadBalancer
  # You could also use NodePort to expose the service at a randomly-generated port
  # type: NodePort
  ports:
  - port: 8080
  selector:
    k8s-app: fulfillorderack