apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fulfillorderack
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fulfillorderack
  minReplicas: 11
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
