kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: jenkisnspv 
spec: 
  accessModes: 
    - ReadWriteMany 
  volumeMode: Filesystem 
  resources: 
    requests: 
      storage: 1Gi 
  storageClassName: azuredisk