apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: captureorderack
spec:
  replicas: 10
  template:
    metadata:
      labels:
        task: captureorderack
        k8s-app: captureorderack
    spec:
      containers:
      - name: captureorderack
        image: torosent/captureorderack:latest
        env:
          - name: APPINSIGHT_KEY
            value: "ae038c96-cd43-4643-9814-81a7ea378e48"
          - name: CHALLENGEAPPINSIGHTS_KEY
            value: "534fd36c-889c-4cce-977a-49ccd6d6e5cf"
          - name: TEAMNAME
            value: "team6"
          - name: MONGOURL
            value: "mongodb://etorodb:Aa123456!@etoro-mongo-mongodb/database.default"
          - name: AMQPURL
            value: "amqp://etoro-rabit:Aa123456@rabbit-rabbitmq:5672"
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: Always
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  labels:
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/name: captureorderack-service
  name: captureorderack
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  type: LoadBalancer
  # You could also use NodePort to expose the service at a randomly-generated port
  # type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    k8s-app: captureorderack